[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "petitpotam"
version = "1.0"
requires-python = ">=3.9"
dependencies = [
    "impacket",
]

[project.scripts]
petitpotam = "petitpotam:main"